### ISSUE TITLE
No support for Vulkan?

### ISSUE THREAD

**Issue by coinworld** [Nightmayr-snaps/dolphin-emu-snap#11]
It works fine with OpenGL but I think it would be better to support Vulkan.
I was able to use Vulkan on flatpak or normal dolphin so I think the problem should be either in this package or snapd itself.

Thanks for maintaining this snap :)

**Comment by Nightmayr** [comment]
Hi, I suspect you're probably using the default stable channel which is the 5.0 release before the Vulkan backend was added. If you switch to either the beta or edge channel, you should find the option to select Vulkan. You can switch channels ether through the snap store GUI (dropdown on the top right of the store page), or you could use the terminal `snap refresh dolphin-emulator --beta`
 
The beta release corresponds to the beta releases of dolphin and the edge channel corresponds to the development releases listed on the dolphin downloads page: https://dolphin-emu.org/download/

Snap store channel gui example:
![Screenshot from 2020-11-20 14-02-02](https://user-images.githubusercontent.com/24817147/99808800-4ffc5800-2b39-11eb-8452-f866aa839a34.png)

**Comment by coinworld** [comment]
```
core18               20200929          1932  latest/stable    canonical✓     base
core20               20                634   latest/stable    canonical✓     base
dolphin-emulator     5.0-12716         78    latest/beta      nightmayr      -
gtk-common-themes    0.1-36-gc75f853   1506  latest/stable    canonical✓     -
obs-studio           26.0.2            1157  latest/stable    snapcrafters   -
snapd                2.47.1            9721  latest/stable    canonical✓     snapd
software-boutique    0+git.f633ffb     54    latest/stable/…  flexiondotorg  classic
ubuntu-mate-welcome  20.10.0-bb92cef1  575   latest/stable/…  flexiondotorg  classic
```

I didn't mention that I already have beta version installed, sorry.
The error that dolphin shows is **No Vulkan physical devices available`, and I use Vulkan just fine in anywhere else like Steam (I have RX570)

**Comment by Nightmayr** [comment]
Ah I think this was due to a typo in the path to the Radeon ICD file within my Vulkan wrapper script, I've corrected this in the edge and beta branches. Builds have been triggered, the beta channel should have the new revision in about an hour.

**Comment by Nightmayr** [comment]
Revision 144 is now in the beta channel, should hopefully allow you to use Vulkan now

**Comment by coinworld** [comment]
Thank you for fixing the issue :)

The problem is gone and now it is working fine, so I am closing this issue

**Comment by Nightmayr** [comment]
No problem, thanks for letting me know about this issue with the snap :)
