### ISSUE TITLE
GameCube Adapter won't work with Dolphin

### ISSUE THREAD

**Issue by DreamyNX** [Nightmayr-snaps/dolphin-emu-snap#12]
I'm using Dolphin Emulator on Ubuntu 20.04, on latest/edge (Dolphin-13452).

Even though I followed the guide on the Wiki for the GameCube adapter [here](https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin#Linux), it still won't work in this version of Dolphin. I set the controller to GameCube Adapter for Wii U, and in the Configure window, it says:

> Error Opening Adapter: Input/Output Error

I can't do anything from there. I can't tell if this is user error or an issue with dolphin-emu-snap.

**Comment by Nightmayr** [comment]
Hi, I suspect this is probably due to a problem with permissions with the snap. Does running the snap from the command line `dolphin-emulator.dolphin-emu` provide any additional clues? Unfortunately I haven't been able to test this on my end as I don't have GameCube adapter and a GameCube controller (looking to acquire one to be able to test though).

Additionally if you could download the `snappy-debug` snap and keep it running in the background whilst you try to configure the adapter, hopefully it should log permission denials and give an indication on how to fix this.

**Comment by DreamyNX** [comment]
Hello! Running it through the command line yielded nothing but libpng warnings (known incorrect sRGB profile), presumably due to me using the game covers option in Grid Mode. Other than that, the game covers and interface function perfectly.

I tried using snappy-debug, but all I got was [this](https://pastebin.com/44Q0gPAR). I'm not sure how to operate snappy-debug though, so I might not be doing it right.. Nothing popped up about USB access as far as I know.

**Comment by Nightmayr** [comment]
Ah okay, the log doesn't show anything related to USB access. Just to narrow this down further, are you able to confirm the adapter works with the development version from the PPA?

**Comment by DreamyNX** [comment]
I actually can't even install from the PPA. [This](https://pastebin.com/MtuNaqKJ) is what happened when I tried to do that.

**Comment by Nightmayr** [comment]
Seems like the PPA hasn't been updated to allow for 20.04 installs, the only other thing I can think of would be to manually compile. I should have the adapter and controller pretty soon so I'll hopefully be able to test sometime this week. I'll try providing an update with my findings.

**Comment by Nightmayr** [comment]
I was able to test this today, and could confirm what you were seeing. I've made a change to the snap https://github.com/Nightmayr-snaps/dolphin-emu-snap/pull/13, which allowed dolphin to recognise and use the gamecube adapter. A build has been triggered for the edge channel, revision 214 should have these changes.

Once you have updated the snap you'll have to enable the `raw-usb` permission. You can do this via the snap store gui dolphin-emulator store page, click on permissions and enable the "Access USB hardware directly" permission. Alternatively you could use the command line `snap connect dolphin-emulator:raw-usb`

Once that's done you should hopefully be able to use the Gamecube adapter

**Comment by DreamyNX** [comment]
Hey, it works! Thanks for all your help, I really appreciate it!

**Comment by Nightmayr** [comment]
No problem, thanks for letting me know this was an issue :)

**Comment by mac-chaffee** [comment]
While installing this snap on a fresh computer and trying to get the GameCube adapter to work, I found this thread to be very helpful. I kept missing bits and pieces, so I'll summarize for any future visitors:

## How to get the GameCube Adapter to work with this snap

### Steps
1. Ensure you are using the **latest/edge** channel of this snap: `snap refresh dolphin-emulator --channel=latest/edge`.
2. Follow the instructions [here](https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin#Linux) to set up udev rules to allow access to the GameCube adapter
3. Insert both USB cables from your GameCube adapter into your computer (or re-insert if they were already inserted)
4. Set the switch on your adapter to "Wii-U", not "PC".
5. Run `snap connect dolphin-emulator:raw-usb` (you only have to run this once)
6. Launch Dolphin
7. Click on "Controllers"
8. For all four ports, set them to "GameCube Adapter for Wii U"
9. If everything worked, when you click "Configure", you should see "Adapter detected"

### Troubleshooting
These are possible messages you could see when you click "Configure":
* `Error Opening Adapter: Access denied (insufficient permissions)`
    - Did you create the udev rules in step 2? Did you reload the rules exactly as directed, including either restarting or re-plugging?
* `Input/Output error`
    - Did you do step 5?
    - Are you using the `latest/edge` channel? `snap info dolphin-emulator | grep tracking`
* `No adapter detected`
    - Are both cables plugged in? 
    - Is the switch on the adapter in "Wii-U" mode?
    - Are you using the `latest/edge` channel? `snap info dolphin-emulator | grep tracking`
    
Remember that most of these troubleshooting steps require restarting Dolphin before the changes take effect.
