### ISSUE TITLE
read/write permission from an hdd mount

### ISSUE THREAD

**Issue by Fuseteam** [Nightmayr-snaps/dolphin-emu-snap#19]
i have an ubuntu 18.04 system with an 120GB SSD and a 1TB HDD
i managed to mount the HDD in ~/drive but there is no way for snap to read from it. are there specific connections is should enable to grant permission? or maybe i could mount it in a certain path?

**Comment by Nightmayr** [comment]
For a HDD mount normally you would enable the `removable-media` permission `snap connect dolphin-emulator:removable-media`, however I believe it applies to storage mounted in the following locations: `/media`, `/run/media`, `/mnt`. Seeing as your HDD is mounted in your home directory I don't think this would apply but you can give it a go regardless. The snap should be able to access your home directory and non hidden subdirectories as it has the `home` interface automatically connected, but I haven't ever tested mounting a drive in the home directory.

**Comment by Fuseteam** [comment]
appearently it doesn't seem to access mounted subdirectories in the home hmm interesting. i'll try to see if it works with /media thanks

**Comment by Fuseteam** [comment]
ah cool it works with /media that interesting to know hmmm

**Comment by Nightmayr** [comment]
Nice, yeah not sure about why the home directory mount didn't work. If that's something you need or have questions about the snapcraft forum might be a good place to ask about it https://forum.snapcraft.io/

**Comment by Fuseteam** [comment]
yeah thanks, i guess for now i'll just close this issue.
