### ISSUE TITLE
Stopped working on Ubuntu 21.10

### ISSUE THREAD

**Issue by joaorb64** [Nightmayr-snaps/dolphin-emu-snap#20]
After upgrading to Ubuntu 21.10, I get the following error when trying to run Dolphin:

```
/snap/dolphin-emulator/526/usr/local/bin/dolphin-emu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /var/lib/snapd/lib/gl/libEGL.so.1)
```

I don't know much about snaps, but from what I've been searching about this problem, I believe 21.10 changed glibc to 2.34 and core20 is tied to version 2.33.
I'm not sure if it's something that snaps should package from now on or if this is going to be fixed on snapd/core side.

**Comment by Nightmayr** [comment]
Thanks for reporting this, I suspect you're using an Nvidia GPU with the proprietary drivers, in which then I think the error you're seeing has been reported on this Snapcraft forum post: https://forum.snapcraft.io/t/egl-using-snaps-on-impish-seem-to-be-broken-when-using-the-nvidia-proprietary-driver/25715 . This will require solving on snapd's side

**Comment by joaorb64** [comment]
Yes, this is exactly my case. I see, so I'll close this issue since it's on snapd's end. Thanks for the response!
