### ISSUE TITLE
ISO aren't starting using command line

### ISSUE THREAD

**Issue by Xenoxis** [Nightmayr-snaps/dolphin-emu-snap#29]
Hello, i'm trying to start an ISO game file from shell using this command :

`/snap/bin/dolphin-emulator.dolphin-emu -e "My Full Path File"`

But dolphin complain as like the file was corrupted ("is an invalid GCM/ISO file, or is not a GC/WII ISO").

I tried with some of my iso from my collection, which run great on dolphin Windows (the latest beta version 5.0-17296), but all aren't working.
I have the latest beta snap package of dolphin
`Dolphin-emulator                5.0-17269        794    latest/beta    nightmayr   -`

Maybe i'm doing something wrong, but currently I don't know what to do.

Thanks

**Comment by Nightmayr** [comment]
Hi @Xenoxis, I just gave this a go and had a similar error. Is your ISO on an external drive (i.e is it mounted at `/mnt`) this was the case for me. Running `snap connect dolphin-emulator:removable-media` allowed me to launch with the `-e` flag.

I've noticed you've closed this issue. Did you manage to resolve this yourself?

**Comment by Xenoxis** [comment]
Hi @Nightmayr, thanks for your reply, but yes absolutely I've solve this issue myself by connecting the `removable-media` plugin as you've just said.

My ISO are in a folder mounted in /media.
