### ISSUE TITLE
Gtk:ERROR

### ISSUE THREAD

**Issue by rafanpiro** [Nightmayr-snaps/dolphin-emu-snap#8]
i have installed the dolphin emulator from the snap in ubuntu 20.04 64 bits and nothing happens when running the app so I tried from command line.
Some sort of problem with the Gtk module. As it is within the snap and I am new to this, I do not know how to fix. I have re-installed several times and always the same problem.

OUTPUT:
usr/lib$ dolphin-emulator.dolphin-emu
Gtk-Message: 23:29:30.938: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:29:30.943: Failed to load module "canberra-gtk-module"

(dolphin-emu:186614): Gtk-WARNING **: 23:29:31.725: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/dolphin-emulator/84/data-dir/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Abortado (`core' generado)

**Comment by Nightmayr** [comment]
Thanks for opening this issue, can I confirm which channel you're using for the dolphin-emulator snap? `snap info dolphin-emulator` should show the installed version

**Comment by rafanpiro** [comment]
I am pasting all the command info output here:

/usr/lib$ snap info dolphin-emulator
name:      dolphin-emulator
summary:   A Wii/GameCube Emulator
publisher: Umayr Saghir (nightmayr)
store-url: https://snapcraft.io/dolphin-emulator
contact:   https://github.com/Nightmayr/dolphin-snap/issues
license:   GPL-2.0
description: |
  Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii.
  It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with
  several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer,
  and even more.
  
  This snap is not necessarily endorsed or officially maintained by the upstream developers.
  
  Upstream Project: https://dolphin-emu.org/ snapcraft.yaml Build Definition:
  https://github.com/Nightmayr-snaps/dolphin-snap
  
  **Please report any bugs/issues with this snap here:**
  https://github.com/Nightmayr-snaps/dolphin-emu-snap/issues
commands:
  - dolphin-emulator.dolphin-emu
  - dolphin-emulator.dolphin-emu-nogui
snap-id:      heVhLF9j4R3PQTlqsmUYk2VXWy2Xa7Er
tracking:     latest/stable
refresh-date: 8 days ago, at 12:26 CET
channels:
  latest/stable:    5.0       2020-10-11  (84) 133MB -
  latest/candidate: ↑                                
  latest/beta:      5.0-12716 2020-10-08  (78) 248MB -
  latest/edge:      5.0-12958 2020-11-03 (113)  76MB -
installed:          5.0                   (84) 133MB -

**Comment by Nightmayr** [comment]
Cool so it looks like you're using the 5.0 version from the stable version. I've made some edits to the stable version and have pushed it into the candidate channel. Can you switch to the candidate channel using `snap refresh dolphin-emulator --candidate` and let me know if the snap works?

**Comment by rafanpiro** [comment]
Same error with candidate. But I changed to edge and it opened with error: Failed to load module "canberra-gtk-module". It worked but when loading Wario World of GC it failed with a GC error on screen: restart the GC.

**CANDIDATE:**
Here is both commands output:
**/usr/lib$ snap info dolphin-emulator**
name:      dolphin-emulator
summary:   A Wii/GameCube Emulator
publisher: Umayr Saghir (nightmayr)
store-url: https://snapcraft.io/dolphin-emulator
contact:   https://github.com/Nightmayr/dolphin-snap/issues
license:   GPL-2.0
description: |
  BLA BLA BLA
commands:
  - dolphin-emulator.dolphin-emu
  - dolphin-emulator.dolphin-emu-nogui
snap-id:      heVhLF9j4R3PQTlqsmUYk2VXWy2Xa7Er
tracking:     latest/candidate
**refresh-date: hoy a las 16:55 CET**
channels:
  latest/stable:    5.0       2020-10-11  (84) 133MB -
  latest/candidate: 5.0       2020-11-03 (114) 139MB -
  latest/beta:      5.0-12716 2020-10-08  (78) 248MB -
  latest/edge:      5.0-12960 2020-11-03 (115)  76MB -
**installed:          5.0                  (114) 139MB -**

**/usr/lib$ dolphin-emulator.dolphin-emu**
Gtk-Message: 17:06:01.202: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:06:01.205: Failed to load module "canberra-gtk-module"

(dolphin-emu:204947): Gtk-WARNING **: 17:06:01.981: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/dolphin-emulator/114/data-dir/icons/Yaru/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

**EDGE**
**usr/lib$ snap info dolphin-emulator**
name:      dolphin-emulator
summary:   A Wii/GameCube Emulator
publisher: Umayr Saghir (nightmayr)
store-url: https://snapcraft.io/dolphin-emulator
contact:   https://github.com/Nightmayr/dolphin-snap/issues
license:   GPL-2.0
description: |
  BLA BLA BLA
commands:
  - dolphin-emulator.dolphin-emu
  - dolphin-emulator.dolphin-emu-nogui
snap-id:      heVhLF9j4R3PQTlqsmUYk2VXWy2Xa7Er
tracking:     latest/edge
refresh-date: hoy a las 17:14 CET
channels:
  latest/stable:    5.0       2020-10-11  (84) 133MB -
  latest/candidate: 5.0       2020-11-03 (114) 139MB -
  latest/beta:      5.0-12716 2020-10-08  (78) 248MB -
  latest/edge:      5.0-12960 2020-11-03 (115)  76MB -
installed:          5.0-12960            (115)  76MB -

**usr/lib$ dolphin-emulator.dolphin-emu**
Gtk-Message: 17:18:12.245: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:18:12.253: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
/usr/share/libdrm/amdgpu.ids: No such file or directory
(dolphin-emu:206060): GLib-GIO-WARNING **: 17:25:15.398: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Gtk-Message: 17:25:16.078: GtkDialog mapped without a transient parent. This is discouraged.
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
/snap/dolphin-emulator/115/usr/bin/xdg-screensaver: 629: /snap/dolphin-emulator/115/usr/bin/xdg-screensaver: xset: not found
Can't locate Encode.pm in @INC (you may need to install the Encode module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 4.
BEGIN failed--compilation aborted at -e line 4.

(dolphin-emu:206060): GLib-GIO-WARNING **: 17:43:38.590: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Gtk-Message: 17:43:38.741: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by rafanpiro** [comment]
I can play now GC Super Mario Sunshine!!!

**Comment by Nightmayr** [comment]
Nice, the beta and edge channels should be quite reliable as they're newer and better supported versions from Dolphin. The 5.0 release because its quite old and is built using a different toolkit from the edge and beta versions, so it requires a lot more custom patches.

I think I may have solved the crashing for the stable version. Would you be able to help test if the candidate version works? You shouldn't lose any save data if you switch channels

**Comment by Nightmayr** [comment]
The latest stable revision no longer produces this error for me, going to close this issue.

**Comment by rafanpiro** [comment]
Working. sorry, I could not check before.
Thanks a lot.
